### ISSUE TITLE
LZO issue

### ISSUE THREAD

**Issue by xcier** [gibbed/Gibbed.Borderlands2#107]
Getting an LZO issue within the newest update. 
Was working before this new update. 

Saves:
[notworkingsave.txt](https://github.com/gibbed/Gibbed.Borderlands2/files/3316742/notworkingsave.txt)

[workingsave.txt](https://github.com/gibbed/Gibbed.Borderlands2/files/3316744/workingsave.txt)
sorry they are in txt since it won't let me send them as .sav they are PS4 saves.

Also like to add the fire drill will only spawn inside the vault. 
As well as the new DLC weapons/items won't spawn in as mission rewards same goes for gearbox weapons.

**Comment by gibbed** [comment]
Could you tell me what version is "before this update"?

**Comment by xcier** [comment]
The newest BL2 update

**Comment by gibbed** [comment]
No, I mean the version of the save editor that this supposedly worked in.

**Comment by xcier** [comment]
1.16

**Comment by gibbed** [comment]
I just downloaded the release build of 1.16 and it isn't working there either...?

**Comment by xcier** [comment]
weird it same I wonder what happened. Either way it currently isn't working.

**Comment by xcier** [comment]
also with the fire drill it is showing up as a legendary and not as a rainbow.

**Comment by The-Hunter716** [comment]
Hey, sorry this is completely off topic, but since it seems like you experienced in the PS field I'd like to ask you a question. I am trying this for the first time and I can't figure out how to make a successful file. I have tried getting a BL2 save from my ps3 and opening the sav file with the save editor but I keep getting a notification saying "Failed to load file: SHA1 hash" I have tried looking for a guide, but all I seem able to find is for PC files.

Would you mind telling me how you are able to modify your files? Please. Thank you.

**Comment by xcier** [comment]
You need bruteforce 4.7.4

**Comment by Desertfox80** [comment]
I just upgraded to brute force newest 4.7.4 version and downloaded the gibbed 1.0.16-with symbols modded my character and it worked. I got a gun that shoots baby butt stallions now so life complete.  I copied and pasted these codes. https://steamcommunity.com/sharedfiles/filedetails/?id=1769787823.
