### ISSUE TITLE
Will Not Load PS3 Saves

### ISSUE THREAD

**Issue by TylerTheeThief** [gibbed/Gibbed.Borderlands2#79]
Every single time I try to load my PS3 save onto Gibbed Save Editor, it won't let me. It allows me to take a PC file and convert into a PS3 save, but I actually want to do the modifying myself. Any suggestions?

**Comment by gibbed** [comment]
You haven't given enough information. What is the actual error you are receiving?

**Comment by TylerTheeThief** [comment]
There isn't an error at all. Gibbed just closes.

**Comment by gibbed** [comment]
1. Are you sure you have [the latest release](https://github.com/gibbed/Gibbed.Borderlands2/releases/latest)?
1. If you are, attach your save file that isn't working to this issue.

**Comment by TylerTheeThief** [comment]
I figured it out. Was trying to load PS3 save under PC save files.

**Comment by thejettdurham** [comment]
I had this same problem, and wanted to clarify the solution since it wasn't obvious to me

When opening a file, you have to select the correct platform from the dropdown list in the File Open dialog. Having the wrong platform selected can cause silent crashes.

![image](https://user-images.githubusercontent.com/5248042/57587532-abbd3e00-74cb-11e9-975a-cab6f1f8f231.png)
