### ISSUE TITLE
DLCExpansionData doesn't work

### ISSUE THREAD

**Issue by jonathancz** [gibbed/Gibbed.Borderlands2#88]
The DLCExpansionData doesn't seem to work. I know that it contains a collection but it won't even let me add anything to the list. Instead, it crashes and no changes are made. Can someone explain it supposed to do exactly? Thanks

**Comment by gibbed** [comment]
As far as I know, Gearbox intended this to be used for DLC expansion data but it went unused due to [the issue documented here](https://github.com/gibbed/Gibbed.Borderlands2/commit/1b14c34848e93b39c71eee3d14235fe15a4b7472).

It's interesting that trying to add an item crashes, I'll put that on my list of things to investigate but it's pretty low priority.

**Comment by gibbed** [comment]
This fix was undone due to it causing crashes with editing other data. Given that DLCExpansionData is extremely low priority, this will have to remain an issue for the time being.

**Comment by gibbed** [comment]
Should be fixed as of https://github.com/gibbed/Gibbed.Borderlands2/commit/4fd656558636a826e091ce4f18cb3ef0dd0044a3.
